#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

KEYDIR=keys
mkdir -p $KEYDIR

bin/clean-all

bin/generate-dns-glue
bin/generate-root-certs
bin/generate-ssh-fingerprint

bin/generate-ksk flatcap.org 2015 01
bin/generate-ksk russon.org  2015 01

bin/generate-zsk flatcap.org 2015 02
bin/generate-zsk flatcap.org 2015 03

bin/generate-zsk russon.org  2015 02
bin/generate-zsk russon.org  2015 03

bin/generate-tlsa
bin/update-serials russon.org.db

bin/sign-zone flatcap.org
bin/sign-zone russon.org

bin/fix-perms

