#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

# cd /var/named

KEYDIR=keys
mkdir -p $KEYDIR
mkdir -p data
mkdir -p dynamic

bin/clean-all

bin/generate-dns-glue
bin/generate-root-certs
bin/generate-ssh-fingerprint

bin/generate-ksk flatcap.org 2015 04
bin/generate-ksk russon.org  2015 04

bin/generate-zsk flatcap.org 2015 04
bin/generate-zsk flatcap.org 2015 05

bin/generate-zsk russon.org  2015 04
bin/generate-zsk russon.org  2015 05

bin/generate-tlsa
bin/update-serials flatcap.org.db
bin/update-serials flatcap.xyz.db
bin/update-serials russon.org.db

bin/sign-zone flatcap.org
bin/sign-zone russon.org

bin/fix-perms

