#!/bin/sh

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

rm -f *.signed
rm -f *.tlsa.inc
rm -f data/*
rm -f dns-glue.inc
rm -f dynamic/*
rm -f keys/*
rm -f named.ca
rm -f ssh-fingerprint.inc

