#!/bin/sh

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
}

trap finish EXIT

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

cd /var/named

rm --force *.signed
rm --force *.tlsa.inc
rm --force dns-glue.inc
rm --force named.ca
rm --force ssh-fingerprint.inc

rm --force --recursive data
rm --force --recursive dynamic
rm --force --recursive "$DNSSEC_KEY_DIR"

rm --force *.db
git checkout -- '*.db'

