#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

# edit named config
#	disable inclusion of   signed domain
#	enable  inclusion of unsigned domain
sed -i -e 's/^#\(.*\.db";\)/\1/' -e 's/^\([^#].*\.db.signed";\)/#\1/' named.conf

# disable zone inclusion of tlsa records
for i in $(grep --ignore-case --files-with-matches "include .*\.tlsa\.db" *.db); do
	sed -i 's/^$INCLUDE .*\.tlsa\.db$/;\0/' $i
done

systemctl try-restart named.service

# tidy up
rm --force *.db.signed
rm --force "$DNSSEC_KEY_DIR"
rm --force dsset-*.

# sync-ds

