#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

KEYDIR=keys
ZONE=russon.org

[ $# = 2 ] || exit 1

rm -fr 201[456]*/

START=$(date "+%s" -d "$1")
END=$(date "+%s" -d "$2")

for ((i = $START; i < $END; i += 86400)); do
	DIR=$(date -d @$i "+%Y%m%d")
	DATE=$(date "+%m%d0400%Y" -d @$i)
	echo
	echo $DIR
	date $DATE
	SALT=$(head -c 1000 /dev/random | sha1sum | cut -b 1-16)
	dnssec-signzone -3 $SALT -S -o $ZONE -K $KEYDIR $ZONE.db
	dnssec-dsfromkey -K $DIR -f $ZONE.db.signed $ZONE > dsset-$ZONE.
	mkdir $DIR
	mv $ZONE.db.signed dsset-$ZONE. $DIR
done

hwclock --hctosys

