#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

KEYDIR="keys"
ZONE="russon.org"

bin/clean-all
mkdir -p "$KEYDIR"

bin/generate-dns-glue
bin/generate-root-certs
bin/generate-ssh-fingerprint

X=$(date "+%Y%m" -d "1 month ago")
START_YEAR=${X:0:4}
START_MONTH=${X:4}
X=$(date "+%Y%m" -d "5 months")
MID_YEAR=${X:0:4}
MID_MONTH=${X:4}

bin/generate-ksk "$ZONE" $START_YEAR $START_MONTH
bin/generate-ksk "$ZONE" $MID_YEAR   $MID_MONTH

MONTHLY=$(date "+%Y%m01" -d "$MID_YEAR-$MID_MONTH-01 -3 months")
echo "MONTHLY = $MONTHLY"
for i in {1..5}; do
	X=$(date "+%Y%m" -d "${MONTHLY} +$i months")
	bin/dnssec-keygen "$ZONE" "${X:0:4}" "${X:4}"
done

bin/set-to-publish-date.sh keys/*
ls -ltr $KEYDIR

