#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

export TZ=UTC

ZONE="russon.org"

[ $# = 2 ] || exit 1

rm -fr 201[456]*/

START=$(date "+%s" --date "$1 +12 hours")
END=$(date "+%s" --date "$2")

for ((i = $START; i < $END; i += 86400)); do
	DIR=$(date --date "@$i" "+%Y%m%d")
	DATE=$(date "+%m%d0400%Y" --date @$i)
	echo
	echo $DIR
	date $DATE
	mkdir $DIR

	sign-zone $ZONE

	dnssec-dsfromkey -K $DIR -f $ZONE.db.signed $ZONE > dsset-$ZONE.
	mv $ZONE.db.signed dsset-$ZONE. $DIR
done

hwclock --hctosys

