#!/usr/bin/perl

use strict;
use warnings;

use Readonly;

our $VERSION = 0.1;

## Configuration

my $changeover    = '10:09:59';
my $dnssec_keygen = '/usr/sbin/dnssec-keygen';

## Parse args

my ($zone, $year, $month) = @ARGV;
defined $zone  || die "Bad zone\n";
defined $year  || die "Bad year\n";
defined $month || die "Bad month\n";

$zone =~ /^[-[:lower:]\d.]+$/msxi;
$year =~ /^\d\d\d\d+$/msx;
$month =~ /^(0?[1-9]|1[012])$/msx;

## Build the command to execute

Readonly my $P_DAY => 3;
Readonly my $A_DAY => 5;
Readonly my $I_DAY => 5;
Readonly my $D_DAY => 7;

my $command =
  sprintf '%s -a NSEC3RSASHA1 -b 2048 -K keys -P %s -A %s -I %s -D %s %s',
  $dnssec_keygen,
  datetime ($year, $month,     $P_DAY),
  datetime ($year, $month,     $A_DAY),
  datetime ($year, $month + 1, $I_DAY),
  datetime ($year, $month + 1, $D_DAY),
  lc $zone;

## Execute the command

print "Executing: $command\n";
printf "\e[1;32mCreating Zone-Signing Key for $year-$month\e[0m\n";
system $command;

## Convert year/month/day/changeover to an appropriate datetime argument

sub datetime {
	my ($y, $m, $d) = @_;

	Readonly my $MONTHS => 12;

	if ($m > $MONTHS) {
		++$y;
		$m = 1;
	}

	$changeover =~ s/://msxg;

	return sprintf '%s%02d%02d%s', $y, $m, $d, $changeover;
}

