#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

chown --recursive root.named .
chmod --recursive u+rw,g+rX,o-rwx .
chmod --recursive g+w dynamic data
chcon --recursive --user system_u --role object_r .
restorecon -r .

