#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

cd /var/named

chown --recursive root.named .
[ -d data ] && chown --recursive named.named data

chmod --recursive u+rw,g+rX,o-rwx .
[ -d data ]    && chmod --recursive g+w data
[ -d dynamic ] && chmod --recursive g+w dynamic

# .git* may not exist
FILES=(*.git*)
[ -d "$DNSSEC_KEY_DIR" ] && FILES+=("$DNSSEC_KEY_DIR")
[ ${#FILES[@]} -gt 0 ] && chmod --recursive og-rwx bin ${FILES[@]}

chcon --recursive --user system_u --role object_r .
restorecon -r .

