#!/bin/bash

# Copyright 2014-2015 Richard Russon (FlatCap)
# Licensed under the GPLv3

PATH="/var/named/bin:/usr/bin:/usr/sbin"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

[ $# = 0 ] || exit 2

chown --recursive root.named .
[ -d data ] && chown --recursive named.named data

chmod --recursive u+rw,g+rX,o-rwx .
[ -d data ]    && chmod --recursive g+w data
[ -d dynamic ] && chmod --recursive g+w dynamic

# .git* may not exist
FILES=(*.git*)
[ -d "$DNSSEC_KEY_DIR" ] && FILES+=("$DNSSEC_KEY_DIR")
[ ${#FILES[@]} -gt 0 ] && chmod --recursive og-rwx bin ${FILES[@]}

chcon --recursive --user system_u --role object_r .
restorecon -r .

