#!/bin/bash

# Copyright 2014-2015 Richard Russon (FlatCap)
# Licensed under the GPLv3

PATH="/var/named/bin:/usr/bin:/usr/sbin"
GLUE_FILE="dns-glue.inc"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

[ $# = 0 ] || exit 2

log_info "Generate DNS Glue"
if [ -f "$GLUE_FILE" ]; then
	log_warning "\talready exists"
	exit 0
fi

OUT=()
for i in {1..5}; do
	H=$(host "ns$i.linode.com")
	OUT+=("$(echo "$H" | sed -e 's/IPv6 /AAA/' -e 's/\.com has//' -e 's/address/A/')")
done

(
	echo "; Maintain glue to our external dns"
	printf "%s\n" "${OUT[@]}" | column -t
) > "$GLUE_FILE"

echo -e "\t$GLUE_FILE"

exit 0

