#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

echo -e "\e[1;32mGenerate Root Certificates\e[0m"

dig +norecurse +nostats +nocomments +nocmd @a.root-servers.net | grep --invert-match "^;" | LANG=C sort > named.ca

