#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

for ZONE in flatcap.org russon.org; do
	(
	echo '; TLSA records for services'
	for PORT in 443 993 995; do
		danetool --load-certificate /etc/pki/tls/${ZONE}.crt --proto tcp --port $PORT --host $ZONE --tlsa-rr
	done
	) > ${ZONE}.tlsa.inc
done

bin/fix-perms

