#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

echo -e "\e[1;32mGenerate TLSA Records for Services\e[0m"

for ZONE in $DNSSEC_DOMAINS; do
	(
	echo '; TLSA records for services'
	for PORT in $DNSSEC_PORTS; do
		danetool --load-certificate /etc/pki/tls/$ZONE.crt --proto tcp --port $PORT --host $ZONE --tlsa-rr
	done
	) > $ZONE.tlsa.inc
done

fix-perms

