#!/bin/bash

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
}

trap finish EXIT

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

cd /var/named

[ $# = 0 ] && exit 2

echo -e "\e[1;32mGenerate TLSA Records for Services\e[0m"
for ZONE in $@; do
	if [ -f "$ZONE.tlsa.inc" ]; then
		echo -e "\t\e[1;33m$ZONE already exists\e[0m"
		continue
	fi

	echo -e "\t$ZONE"
	(
	echo '; TLSA records for services'
	for PORT in $DNSSEC_PORTS; do
		danetool --load-certificate /etc/pki/tls/$ZONE.crt --proto tcp --port $PORT --host $ZONE --tlsa-rr
	done
	) > $ZONE.tlsa.inc
done

exit 0

