#!/bin/bash

# Copyright 2014-2015 Richard Russon (FlatCap)
# Licensed under the GPLv3

CERT_FILE="named.ca"
PATH="/var/named/bin:/usr/bin:/usr/sbin"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

[ $# = 0 ] || exit 2

log_info "aenerate Root Certificates"
if [ -f "$CERT_FILE" ]; then
	log_warning "\talready exists"
	exit 0
fi

OUT="$(dig +norecurse +nostats +nocomments +nocmd @a.root-servers.net)"

echo "$OUT" | grep --invert-match "^;" | LANG=C sort > "$CERT_FILE"

echo -e "\t$CERT_FILE"

exit 0

