#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

# cd /var/named

(
	echo '; Maintain glue to our external dns'
	for i in {1..5}; do
		host ns$i.linode.com | sed -e 's/IPv6 /AAA/' -e 's/\.com has//' -e 's/address/A/'
	done | column -t
) > dns-glue.inc

