#!/bin/bash

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
}

trap finish EXIT

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

cd /var/named

echo -e "\e[1;32mGenerate Key-Signing Key\e[0m"

if [ ! $# = 1 -a ! $# = 3 ]; then
	echo "Usage: ${0##*/} ZONE [YEAR MONTH]"
	exit 2
fi

ZONE="$1"
YEAR="${2:-$(date '+%Y')}"
MONTH="${3:-$(date '+%m')}"
DAY="01"
TIME="040000"
VALID="6 months + 2 days"

P="$(date "+%Y%m%d" --date "$YEAR-$MONTH-$DAY - 2 days")$TIME"
A="$(date "+%Y%m%d" --date "$YEAR-$MONTH-$DAY")$TIME"
I="$(date "+%Y%m%d" --date "$YEAR-$MONTH-$DAY + $VALID")$TIME"
D="$(date "+%Y%m%d" --date "$YEAR-$MONTH-$DAY + $VALID + 2 days")$TIME"

# echo P=$P
# echo A=$A
# echo I=$I
# echo D=$D
# exit

mkdir --parents "$DNSSEC_KEY_DIR"

dnssec-keygen -a NSEC3RSASHA1 -n ZONE -K "$DNSSEC_KEY_DIR" -b 4096 -f KSK -P $P -A $A -I $I -D $D $ZONE

exit 0

