#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

echo -e "\e[1;32mGenerate SSH Fingerprints\e[0m"
if [ -f "ssh-fingerprint.inc" ]; then
	echo -e "\talready exists"
	exit 0
fi

(
	echo '; SSH fingerprints'
	ssh-keygen -r @
) > ssh-fingerprint.inc

