#!/bin/bash

FP_FILE="ssh-fingerprint.inc"
PATH="/var/named/bin:/usr/bin:/usr/sbin"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

[ $# = 0 ] || exit 2

log_info "Generate SSH Fingerprints"
if [ -f "$FP_FILE" ]; then
	log_warning "\talready exists"
	exit 0
fi

OUT=$(ssh-keygen -r @)

(
	echo '; SSH fingerprints'
	echo "$OUT"
) > "$FP_FILE"

echo -e "\t$FP_FILE"

exit 0

