#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

echo -e "\e[1;32mGenerate Zone-Signing Key\e[0m"

if [ ! $# = 1 -a ! $# = 3 ]; then
	echo "Usage: ${0##*/} ZONE [YEAR MONTH]"
	exit 1
fi

ZONE="$1"
YEAR="${2:-$(date '+%Y')}"
MONTH="${3:-$(date '+%m')}"
DAY="06"
TIME="080000"
VALID="1 month"

P="$(date "+%Y%m%d" -d "$YEAR-$MONTH-$DAY - 2 days")$TIME"
A="$(date "+%Y%m%d" -d "$YEAR-$MONTH-$DAY")$TIME"
I="$(date "+%Y%m%d" -d "$YEAR-$MONTH-$DAY + $VALID")$TIME"
D="$(date "+%Y%m%d" -d "$YEAR-$MONTH-$DAY + $VALID + 2 days")$TIME"

# echo P=$P
# echo A=$A
# echo I=$I
# echo D=$D
# exit

KEYDIR=keys
mkdir -p $KEYDIR

dnssec-keygen -a NSEC3RSASHA1 -n ZONE -K $KEYDIR -b 2048 -P $P -A $A -I $I -D $D $ZONE

