#!/bin/bash

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || echo -e "\e[1;31m${0##*/} failed: $RETVAL\e[0m"
}

trap finish EXIT

PATH="/var/named/bin:/usr/bin:/usr/sbin"
CERT_FILE="named.ca"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

cd /var/named

[ $# = 0 ] || exit 2

echo -e "\e[1;32mGenerate Root Certificates\e[0m"
if [ -f "$CERT_FILE" ]; then
	echo -e "\t\e[1;33malready exists\e[0m"
	exit 0
fi

OUT="$(dig +norecurse +nostats +nocomments +nocmd @a.root-servers.net)"

echo "$OUT" | grep --invert-match "^;" | LANG=C sort > "$CERT_FILE"

echo -e "\t$CERT_FILE"

exit 0

