#!/bin/bash

RUSSON="https://www.gkg.net/ws/domain/russon.org/ds"
PASSWD="--user flatcap:ha2meiChu8"

# LIST all DS
# Responses:
#	200 OK
#	401 Unauthorized
#	404 Not Found
# curl -s $PASSWD \
# 	-H "Accept: application/json" \
# 	-X GET \
# 	$RUSSON | json_reformat

# GET specific DS
# Responses:
#	200 OK
#	401 Unauthorized
#	404 Not Found
# curl -s $PASSWD \
# 	-H "Accept: application/json" \
# 	-X GET \
# 	$RUSSON/843D7568BD35472EA283A01BEC87B24528C91CC3 | json_reformat

# DELETE a DS
# Responses:
#	204 No Content
#	401 Unauthorized
#	403 Forbidden
#	404 Not Found
# curl -s $PASSWD \
# 	-H "Accept: application/json" \
# 	-o /dev/null \
# 	-w "%{http_code}" \
# 	-X DELETE \
# 	"$RUSSON/B15A9A27528D250682D7C3ED91B9F4ED270FE271AC48A2D8CB75975171506822"

# CREATE a DS
# Responses:
#	201 Created
#	401 Unauthorized
#	403 Forbidden
#	404 Not Found
#	415 Unsupported Media Type
curl -s $PASSWD \
# 	-H "Accept: application/json" \
# 	-o /dev/null \
# 	-w "%{http_code}" \
# 	-X POST \
# 	-d '{ "digest":"B15A9A27528D250682D7C3ED91B9F4ED270FE271AC48A2D8CB75975171506822", "digestType":"2", "algorithm":"7", "keyTag":"19956", "maxSigLife":"3456000" }' \
# 	$RUSSON

