#!/bin/bash

set -x

# curl --user flatcap:ha2meiChu8 -i -H "Accept: application/json" https://www.gkg.net/ws/domain/russon.org/ds
curl --user flatcap:ha2meiChu8 -i https://www.gkg.net/ws/domain/russon.org/ds

