#!/bin/bash

if [ $# = 0 ]; then
	echo "Usage: ${0##*/} {zonefile...}"
	exit 1
fi

SERIAL="$(date '+%Y%m%d00')"

for i in "$@"; do
	FILE="$i"
	ZONE="${i%.db}"
	ZONE_SERIAL=$(/usr/sbin/named-checkzone $ZONE $FILE | egrep -ho '[0-9]{10}')
	if [ -z "$ZONE_SERIAL" ]; then
		echo "Bad zone file: $FILE"
		exit 1
	fi

	[ $ZONE_SERIAL -gt $SERIAL ] && SERIAL=$ZONE_SERIAL
done

: $((SERIAL++))

for i in "$@"; do
	FILE="$i"
	ZONE="${i%.db}"
	sed -i "s/\<[0-9]\{10\}\>/$SERIAL/" $FILE
done

