#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

if [ $# = 0 ]; then
	set -- $DNSSEC_KEY_DIR/*.{key,private}
fi

log_info "Set to Publish Date"
for f in "$@"; do
	FILE_DATE=$(awk '/Publish/{ print $3 ? $3 : $2 }' $f)
	if [ -z "$FILE_DATE" ]; then
		echo -e "\tIgnoring: $f"
		continue
	fi

	echo -e "\t${FILE_DATE:0:8} - $f"
	touch --date "${FILE_DATE:0:8}" "$f"
done

exit 0

