#!/bin/bash

# Copyright 2014-2015 Richard Russon (FlatCap)
# Licensed under the GPLv3

PATH="/var/named/bin:/usr/bin:/usr/sbin"
source log.sh

export TZ="UTC"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

shopt -s nullglob

function finish()
{
	local RETVAL=$?
	[ $RETVAL = 0 ] || log_error "${0##*/} failed: $RETVAL"
}

trap finish EXIT

cd /var/named

[ ! -d "$DNSSEC_KEY_DIR" ] && exit 0

if [ $# = 0 ]; then
	FILES=("$DNSSEC_KEY_DIR"/K*.key)
else
	for i in "$@"; do
		FILES=("$DNSSEC_KEY_DIR"/K${i}.*.key)
	done
fi

[ ${#FILES[@]} = 0 ] && exit 0

for type in "key-signing" "zone-signing"; do
	log_info "$type keys"
	ls -1 --sort=time --reverse "$DNSSEC_KEY_DIR"/*.key | while read x; do
		grep --quiet $type "$x" || continue
		echo $x
		grep -e "Activate" -e "Inactive" $x | sed -e 's/^; /\t/' -e 's/\([0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)/\1-\2-\3 \4:\5:\6/'
	done
	echo
done

