#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

shopt -s nullglob

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

[ ! -d "$DNSSEC_KEY_DIR" ] && exit 0

for type in "key-signing" "zone-signing"; do
	echo
	echo -e "\e[1;32m$type keys\e[0m"
	ls -1 --sort=time --reverse "$DNSSEC_KEY_DIR"/*.key | while read x; do
		grep --quiet $type "$x" || continue
		echo $x
		grep -e "Activate" -e "Inactive" $x | sed -e 's/^; /\t/' -e 's/\([0-9][0-9][0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)/\1-\2-\3 \4:\5:\6/'
	done
done

