#!/bin/bash

PATH="/var/named/bin:/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

cd /var/named

if [ $# != 1 ]; then
	echo "Usage: ${0##*/} ZONE"
	exit 1
fi

KEYDIR=keys
ZONE=$1

mkdir -p $KEYDIR

SALT=$(head -c 1024 /dev/random | sha1sum)
SALT=${SALT:0:16}
SALT=${SALT^^}

# Sign the zone, and write it out to a file named zone.signed
echo -e "\e[1;32mSign zone $ZONE\e[0m (Salt: $SALT)"
dnssec-signzone -3 $SALT -S -o $ZONE -K $KEYDIR $ZONE.db
mv dsset-$ZONE. $KEYDIR

