#!/bin/bash

PATH="/usr/bin:/usr/sbin"

set -o errexit	# set -e
set -o nounset	# set -u

renice --priority 19 --pid $$ > /dev/null
ionice --class 3     --pid $$ > /dev/null

# cd /var/named

if [ $# != 1 ]; then
	echo "Usage: ${0##*/} ZONE"
	exit 1
fi

KEYDIR=keys
ZONE=$1

mkdir -p $KEYDIR

# Sign the zone, and write it out to a file named zone.signed
SALT=$(head -c 1000 /dev/random | sha1sum | cut -b 1-16)
dnssec-signzone -3 $SALT -S -o $ZONE -K $KEYDIR ${ZONE}.db
mv dsset-${ZONE}. $KEYDIR

