#!/bin/bash

function usage()
{
	echo "Usage: ${0##*/} [zonefile...]"
	exit 1
}


shopt -s nullglob

if [ $# = 0 ]; then
	FILE_LIST=(*.db)

	if [ ${#FILE_LIST[@]} = 0 ]; then
		echo "No zone files"
		exit 1
	fi
else
	FILE_LIST=($@)
fi

SERIAL="$(date '+%Y%m%d00')"

for FILE in ${FILE_LIST[@]}; do
	if [ ! -s "$FILE" ]; then
		echo "File doesn't exist: $FILE"
		continue
	fi

	ZONE="${FILE%.db}"

	ZONE_SERIAL=$(/usr/sbin/named-checkzone $ZONE $FILE | egrep -ho '[0-9]{10}')
	if [ -z "$ZONE_SERIAL" ]; then
		echo "Bad zone file: $FILE"
		exit 1
	fi

	[ $ZONE_SERIAL -gt $SERIAL ] && SERIAL=$ZONE_SERIAL
done

: $((SERIAL++))

echo -e "\e[1;32mUpdate zone file serial numbers\e[0m"
for FILE in ${FILE_LIST[@]}; do
	ZONE="${FILE%.db}"
	sed -i "s/\<[0-9]\{10\}\>/$SERIAL/" $FILE
	echo -e "\t$ZONE" "$SERIAL"
done

